-- AlterTable
ALTER TABLE "conteudos" ALTER COLUMN "titulo" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "eventos" ALTER COLUMN "titulo" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "data" SET DATA TYPE VARCHAR(15),
ALTER COLUMN "horario" SET DATA TYPE VARCHAR(8);
